# Generated by Django 6.0.4 on 2026-04-10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0005_buffetplan_buffetsession_wastelog_buffetround"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bill_no", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("FINALIZED", "Finalized"), ("PAID", "Paid")], default="DRAFT", max_length=20)),
                ("subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("vat_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("coperto_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("service_charge_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("waste_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("discount_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("grand_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bills", to="tenants.branch")),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="bill", to="orders.order")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bills", to="tenants.tenant")),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("branch", "bill_no")},
            },
        ),
        migrations.CreateModel(
            name="BillLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_type", models.CharField(choices=[("ORDER_ITEM", "Order Item"), ("COPERTO", "Coperto"), ("SERVICE", "Service"), ("DISCOUNT", "Discount"), ("WASTE", "Waste")], max_length=20)),
                ("source_id", models.CharField(blank=True, max_length=64, null=True)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vat_rate", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="billing.bill")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]