# Generated by Django 6.0.4 on 2026-04-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_receipt_fiscaltransaction_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_count', models.PositiveSmallIntegerField()),
                ('split_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='billing.bill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
