# Generated by Django 6.0.4 on 2026-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('table__isnull', False), models.Q(('status', 'CANCELED'), _negated=True)), fields=('table', 'reserved_for'), name='uniq_active_reservation_per_table_time'),
        ),
    ]
