# Generated by Django 6.0.4 on 2026-04-08 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_reservation_uniq_active_reservation_per_table_time'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=160)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('party_size', models.PositiveSmallIntegerField(default=2)),
                ('quoted_wait_minutes', models.PositiveSmallIntegerField(default=15)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('SEATED', 'Seated'), ('CANCELED', 'Canceled')], default='WAITING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='tenants.branch')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='tables.diningtable')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
