# Generated by Django 6.0.4 on 2026-04-10 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("menu", "0002_allergen_menuitemallergen_menuitem_allergens_and_more"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("STOCK_IN", "Stock In"),
                    ("RECEIVING", "Receiving"),
                    ("STOCK_OUT", "Stock Out"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RecipeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_components",
                        to="tenants.branch",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_components",
                        to="inventory.ingredient",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_components",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_components",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["menu_item_id", "ingredient_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "branch", "menu_item", "ingredient"),
                        name="uniq_recipe_component_per_menu_item_ingredient",
                    )
                ],
            },
        ),
    ]
