from django.urls import path

from .views import (
    DiningTableDetailView,
    DiningTableListCreateView,
    FloorPlanDetailView,
    FloorPlanListCreateView,
    ReservationArrivedView,
    ReservationCancelView,
    ReservationDetailView,
    ReservationListCreateView,
    TableCloseSessionView,
    TableLiveStatusView,
    TableMergeView,
    TableOpenSessionView,
    TableSessionListView,
    TableSplitView,
    WaitlistEntryCallView,
    WaitlistEntryCancelView,
    WaitlistEntryDetailView,
    WaitlistEntryListCreateView,
    WaitlistEntrySeatView,
)

urlpatterns = [
    path("floor-plans", FloorPlanListCreateView.as_view(), name="floor-plans-list-create"),
    path("floor-plans/<int:pk>", FloorPlanDetailView.as_view(), name="floor-plans-detail"),
    path("tables", DiningTableListCreateView.as_view(), name="tables-list-create"),
    path("tables/live-status", TableLiveStatusView.as_view(), name="tables-live-status"),
    path("tables/merge", TableMergeView.as_view(), name="tables-merge"),
    path("tables/split/<int:pk>", TableSplitView.as_view(), name="tables-split"),
    path("tables/<int:pk>", DiningTableDetailView.as_view(), name="tables-detail"),
    path("tables/<int:pk>/open-session", TableOpenSessionView.as_view(), name="tables-open-session"),
    path("tables/<int:pk>/close-session", TableCloseSessionView.as_view(), name="tables-close-session"),
    path("table-sessions", TableSessionListView.as_view(), name="table-sessions-list"),
    path("reservations", ReservationListCreateView.as_view(), name="reservations-list-create"),
    path("reservations/<int:pk>", ReservationDetailView.as_view(), name="reservations-detail"),
    path("reservations/<int:pk>/arrived", ReservationArrivedView.as_view(), name="reservations-arrived"),
    path("reservations/<int:pk>/cancel", ReservationCancelView.as_view(), name="reservations-cancel"),
    path("waitlist", WaitlistEntryListCreateView.as_view(), name="waitlist-list-create"),
    path("waitlist/<int:pk>", WaitlistEntryDetailView.as_view(), name="waitlist-detail"),
    path("waitlist/<int:pk>/call", WaitlistEntryCallView.as_view(), name="waitlist-call"),
    path("waitlist/<int:pk>/seat", WaitlistEntrySeatView.as_view(), name="waitlist-seat"),
    path("waitlist/<int:pk>/cancel", WaitlistEntryCancelView.as_view(), name="waitlist-cancel"),
]
