# Generated by Django 6.0.4 on 2026-04-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_addongroup_addonitem_menuvariant'),
        ('orders', '0007_orderevent'),
        ('printers', '0001_initial'),
        ('tenants', '0002_subscriptionplan_branch_address_branch_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='acked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printjob',
            name='kitchen_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='orders.kitchenticket'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('ACKED', 'Acknowledged'), ('FAILED', 'Failed')], default='QUEUED', max_length=20),
        ),
        migrations.CreateModel(
            name='PrinterRouteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_route_rules', to='tenants.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_route_rules', to='menu.menucategory')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_route_rules', to='menu.menuitem')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_rules', to='printers.printer')),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
    ]
