# Generated by Django 6.0.4 on 2026-04-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_allergen_menuitemallergen_menuitem_allergens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('min_select', models.PositiveSmallIntegerField(default=0)),
                ('max_select', models.PositiveSmallIntegerField(default=1)),
                ('required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_groups', to='menu.menuitem')),
            ],
            options={
                'ordering': ['menu_item_id', 'name'],
                'unique_together': {('menu_item', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AddonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.addongroup')),
            ],
            options={
                'ordering': ['addon_group_id', 'name'],
                'unique_together': {('addon_group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.menuitem')),
            ],
            options={
                'ordering': ['menu_item_id', 'name'],
                'unique_together': {('menu_item', 'name')},
            },
        ),
    ]
