# Generated by Django 6.0.4 on 2026-04-09 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_kitchenticket'),
        ('tables', '0003_waitlistentry'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('order_no__isnull', False)), fields=('branch', 'order_no'), name='uniq_order_no_per_branch'),
        ),
    ]
