# Generated by Django 6.0.4 on 2026-04-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_no_order_uniq_order_no_per_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['course', 'id']},
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='course',
            field=models.CharField(blank=True, choices=[('STARTER', 'Starter'), ('MAIN', 'Main'), ('DESSERT', 'Dessert'), ('DRINK', 'Drink'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='course',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('MAIN', 'Main'), ('DESSERT', 'Dessert'), ('DRINK', 'Drink'), ('OTHER', 'Other')], default='MAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('HELD', 'Held'), ('SENT_TO_KITCHEN', 'Sent to Kitchen'), ('PARTIALLY_SERVED', 'Partially Served'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='OPEN', max_length=30),
        ),
    ]
