# Generated by Django 6.0.4 on 2026-04-11 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_customer_order_customer_customervisit_loyaltyrule_and_more'),
        ('tenants', '0002_subscriptionplan_branch_address_branch_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('ITEM_ADDED', 'Item Added'), ('ITEM_REMOVED', 'Item Removed'), ('FIRED', 'Fired to Kitchen'), ('COURSE_FIRED', 'Course Fired'), ('HELD', 'Held'), ('PARTIALLY_SERVED', 'Partially Served'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('NOTE_ADDED', 'Note Added'), ('CHANNEL_CHANGED', 'Channel Changed')], max_length=30)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_events', to='tenants.branch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
